-- DO NOT EDIT THIS FILE (synced by HIT)
-- Source: hit-feature-pack-job-core/migrations/002_add_env_vars_column.sql
-- Feature Pack: job-core

-- Add env_vars column to store task execution parameters
-- This allows passing custom environment variables (e.g., PROJECT_SLUG) when executing tasks.

alter table hit_task_executions add column if not exists env_vars jsonb;
